# Generated by Django 5.2.4 on 2025-07-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='payment_method',
            field=models.CharField(blank=True, help_text="e.g., 'Bank Transfer', 'Cash', 'Credit Card'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The vendor/supplier for this expense.', limit_choices_to={'contact_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('pre_design', 'Pre-Design'), ('schematic_design', 'Schematic Design'), ('design_development', 'Design Development'), ('construction_docs', 'Construction Documents'), ('bidding', 'Bidding'), ('construction', 'Construction'), ('post_construction', 'Post-Construction')], default='pre_design', max_length=30),
        ),
    ]
