# Generated by Django 5.2.4 on 2025-07-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chartofaccounts'),
        ('projects', '0002_financialtransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The account from the CoA to debit/credit', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='asset_description',
            field=models.CharField(blank=True, help_text='Description of the capital asset purchased', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='depreciation_period_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The useful life of the asset in months for depreciation', null=True),
        ),
    ]
