# Generated by Django 5.2.4 on 2025-07-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_financialtransaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='is_debit',
            field=models.BooleanField(default=True, help_text="Is this a debit? (If False, it's a credit)"),
        ),
    ]
