# Generated by Django 5.2.4 on 2025-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chartofaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('accountant', 'Accountant'), ('project_manager', 'Project Manager'), ('engineer', 'Engineer'), ('sales', 'Sales'), ('client', 'Client'), ('admin', 'Admin'), ('employee', 'Employee')], default='client', max_length=20),
        ),
    ]
