# Generated by Django 5.2.4 on 2025-07-26 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_financialtransaction_is_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('client_contract', 'Client Contract'), ('employment_nda', 'Employment NDA')], help_text='The type of contract this template is for.', max_length=50)),
                ('content', models.TextField(help_text='The full text of the contract. Use placeholders like {{client_name}} or {{project_budget}}.')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zoho_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_sign_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_for_signature', 'Sent'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
                ('template_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.contracttemplate')),
            ],
        ),
    ]
