# Generated by Django 5.2.4 on 2025-10-08 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('Interior Designer', 'Interior Designer'), ('Junior Interior Designer', 'Junior Interior Designer'), ('3D Visualizer', '3D Visualizer'), ('Architectural Designer', 'Architectural Designer'), ('Project Manager', 'Project Manager'), ('Site Supervisor', 'Site Supervisor'), ('Furniture Designer', 'Furniture Designer'), ('Lighting Designer', 'Lighting Designer'), ('Drafter(AutoCAD/SketchUp)', 'Drafter(AutoCAD/SketchUp)'), ('Client Relations Executive', 'Client Relations Executive')], max_length=250)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
