# Generated by Django 5.2.4 on 2025-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
