# Generated by Django 5.2.4 on 2025-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Construction', 'Construction'), ('Design', 'Design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='EMP-1001.....', max_length=20, unique=True),
        ),
    ]
