# Generated by Django 5.2.4 on 2025-09-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Completed', 'Completed')], default='Planning', max_length=20)),
                ('channel', models.CharField(help_text='e.g., Social Media, Email, Print', max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('article', 'Blog Article'), ('caption', 'Social Media Caption'), ('email_template', 'Email Template'), ('brand_visual', 'Brand Visual')], max_length=20)),
                ('body', models.TextField(blank=True, help_text='For text-based content like articles or HTML emails.')),
                ('asset_file', models.FileField(blank=True, null=True, upload_to='marketing_assets/')),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(help_text='Store securely!', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sending', 'Sending'), ('Sent', 'Sent')], default='Draft', max_length=20)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('email_template', models.ForeignKey(limit_choices_to={'content_type': 'email_template'}, on_delete=django.db.models.deletion.PROTECT, to='marketing.contentasset')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.mailinglist')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Published', 'Published'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('post_url', models.URLField(blank=True, help_text='URL of the live post after publishing.', null=True)),
                ('content_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.contentasset')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('mailing_lists', models.ManyToManyField(related_name='subscribers', to='marketing.mailinglist')),
            ],
        ),
    ]
