# Generated by Django 5.2.4 on 2025-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_stock_out',
            field=models.BooleanField(default=False),
        ),
    ]
