# Generated by Django 5.2.4 on 2025-07-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes on vendor performance or reliability', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='performance_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vendor rating from 1 to 5', null=True),
        ),
    ]
