# Generated by Django 5.2.4 on 2025-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contact_notes_contact_performance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='item_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
