# Generated by Django 5.2.4 on 2025-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotationitem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='title',
            field=models.CharField(blank=True, help_text="e.g., 'Website Development'", max_length=100, null=True),
        ),
    ]
