# Generated by Django 5.2.4 on 2025-08-29 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_lead_lead_id_quotationitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True, blank=True),
        ),
    ]
